name: august
version: 0.0.1-alpha.0
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  quiver: ^2.0.0
  collection: ^1.1.3
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.3.0
  benchmark_harness: any
