name: august
version: 0.0.1-alpha.0
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  quiver: ^2.0.0
  optional: ^5.0.0
  collection: ^1.14.12
  rxdart: ^0.25.0
  built_value: ^7.1.0
dev_dependencies:
  build_test: ^1.3.1
  build_runner: ^1.7.2
  build_web_compilers: ^2.11.0
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0
  test: ^1.9.4
  benchmark_harness: any
