name: august
version: 0.0.1-alpha.0
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  browser: any
  quiver: ^0.21.4
  collection: ^1.1.3
dev_dependencies:
  test: ^0.12.4
  benchmark_harness: any
