name: august
version: 0.0.1-alpha.0
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  quiver: ^2.0.0
  optional: ^3.1.0
  collection: ^1.14.12
dev_dependencies:
  build_test: ^0.10.11
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  pedantic: ^1.9.0
  test: ^1.9.4
  benchmark_harness: any
